### ISSUE TITLE
gcc No such file or directory

### ISSUE THREAD

**Issue by Brown2Wang** [guoketing/deepwave-order#2]
Emitting ninja build file /mnt/vdh/img_generator/wcw_dev/zyy/FWIGAN/deepwave-order/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.8.2
g++ -pthread -shared -Wl,-z,relro -Wl,-z,now -g -Wl,-z,relro -Wl,-z,now -g /mnt/vdh/img_generator/wcw_dev/zyy/FWIGAN/deepwave-order/build/temp.linux-x86_64-3.6/deepwave/scalar/scalar_cpu.o /mnt/vdh/img_generator/wcw_dev/zyy/FWIGAN/deepwave-order/build/temp.linux-x86_64-3.6/deepwave/scalar/scalar.o /mnt/vdh/img_generator/wcw_dev/zyy/FWIGAN/deepwave-order/build/temp.linux-x86_64-3.6/deepwave/scalar/scalar_wrapper.o -L/usr/local/lib64/python3.6/site-packages/torch/lib -L/usr/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lpython3.6m -o build/lib.linux-x86_64-3.6/scalar1d_cpu_iso_8_float.cpython-36m-x86_64-linux-gnu.so -fopenmp
g++: error: /mnt/vdh/img_generator/wcw_dev/zyy/FWIGAN/deepwave-order/build/temp.linux-x86_64-3.6/deepwave/scalar/scalar_cpu.o: No such file or directory
g++: error: /mnt/vdh/img_generator/wcw_dev/zyy/FWIGAN/deepwave-order/build/temp.linux-x86_64-3.6/deepwave/scalar/scalar.o: No such file or directory
g++: error: /mnt/vdh/img_generator/wcw_dev/zyy/FWIGAN/deepwave-order/build/temp.linux-x86_64-3.6/deepwave/scalar/scalar_wrapper.o: No such file or directory
error: command 'g++' failed with exit status 1

**Comment by guoketing** [comment]
这个包有点问题，你可以去看原来的包，deepwave，https://github.com/guoketing/deepwave，这个应该没问题，但是要求linux系统和gcc
